# Generated by Django 6.1.1 on 2026-10-01 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Процент'), ('AMOUNT', 'Сумма')], default='PERCENT', max_length=10, verbose_name='Тип скидки')),
                ('percent_off', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент')),
                ('amount_off', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки, ₽')),
                ('min_order_sum', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа, ₽')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум применений')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Применено раз')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('guest_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('guest_phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтверждён'), ('IN_PRODUCTION', 'В работе'), ('READY', 'Готов'), ('DELIVERING', 'В доставке'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменён'), ('COMPLAINT', 'Жалоба')], db_index=True, default='NEW', max_length=16, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=12, verbose_name='Оплата')),
                ('options_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Опции на момент заказа')),
                ('inscription', models.CharField(blank=True, default='', max_length=200, verbose_name='Надпись')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='Базовая цена, ₽')),
                ('options_total', models.PositiveIntegerField(default=0, verbose_name='Стоимость опций, ₽')),
                ('inscription_price', models.PositiveIntegerField(default=0, verbose_name='Надпись, ₽')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Доставка, ₽')),
                ('promo_discount', models.PositiveIntegerField(default=0, verbose_name='Скидка, ₽')),
                ('urgency_surcharge', models.PositiveIntegerField(default=0, verbose_name='Наценка за срочность, ₽')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого, ₽')),
                ('promo_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Промокод (текстом)')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('delivery_slot', models.CharField(blank=True, default='', max_length=20, verbose_name='Слот доставки')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочный заказ')),
                ('address_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к заказу')),
                ('delivery_comment', models.TextField(blank=True, default='', verbose_name='Комментарий для курьера')),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая доставка')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATUS', 'Смена статуса'), ('COMPLAINT', 'Жалоба клиента'), ('COMMENT', 'Комментарий'), ('PAYMENT', 'Оплата')], default='STATUS', max_length=12, verbose_name='Тип')),
                ('from_status', models.CharField(blank=True, default='', max_length=16, verbose_name='Из статуса')),
                ('to_status', models.CharField(blank=True, default='', max_length=16, verbose_name='В статус')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('author_label', models.CharField(blank=True, default='', max_length=150, verbose_name='Автор (текст)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'События заказа',
                'ordering': ('-created_at',),
            },
        ),
    ]
