# Generated by Django 6.1.1 on 2026-10-01 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Базовая цена, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Доставка, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inscription_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Надпись, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='options_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость опций, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого, р.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency_surcharge',
            field=models.PositiveIntegerField(default=0, verbose_name='Наценка за срочность, р.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='amount_off',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки, р.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_order_sum',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа, р.'),
        ),
    ]
