# Generated by Django 6.1.1 on 2026-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivery_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Банковской картой онлайн'), ('CASH', 'Наличными в ресторане')], default='CARD', max_length=8, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Токен оплаты'),
        ),
    ]
