# Generated by Django 6.1.1 on 2026-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_backfill_payment_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Банковской картой онлайн'), ('CASH', 'Наличными ...')], default='CARD', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
