# Generated by Django 6.1.1 on 2026-09-30 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название части')),
                ('hint', models.CharField(blank=True, max_length=255, verbose_name='Подсказка')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная часть')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Сочетается с другими')),
                ('requires_text', models.BooleanField(default=False, verbose_name='Требует текста')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в форме')),
            ],
            options={
                'verbose_name': 'Часть торта',
                'verbose_name_plural': 'Части торта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CakePartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название варианта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена варианта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в форме')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='custom_cake.cakepart', verbose_name='Часть')),
            ],
            options={
                'verbose_name': 'Варианты части',
                'verbose_name_plural': 'Варианты частей',
                'ordering': ['part', 'order', 'name'],
                'unique_together': {('part', 'name')},
            },
        ),
    ]
