# Generated by Django 6.1.1 on 2026-10-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakepart',
            name='is_multiple',
        ),
    ]
