# Generated by Django 6.1.1 on 2026-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_cake', '0002_alter_cake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='images/cakes', verbose_name='Картинка'),
        ),
    ]
