# Generated by Django 6.1.1 on 2026-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_cake', '0003_alter_cake_options_alter_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снятый с продажи торт скрыт из каталога', verbose_name='В наличии'),
        ),
    ]
