# Generated by Django 6.1.1 on 2026-10-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cake', '0001_initial'),
        ('ready_cake', '0004_cake_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='restricted_parts',
            field=models.ManyToManyField(blank=True, help_text='Если заполнено — используются только эти части. Если пусто — все части доступны.', to='custom_cake.cakepart', verbose_name='Ограничения кастомизации'),
        ),
    ]
