# Generated by Django 6.1.1 on 2026-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_cake', '0005_cake_restricted_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='ready_cake', verbose_name='Картинка'),
        ),
    ]
